version: "3"

services:
        mysql80:
                container_name: mysql80
                image: mysql:8
                tty: true
                environment:
                  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                command: --default-authentication-plugin=mysql_native_password
        mysql57:
                container_name: mysql57
                image: mysql:5.7
                tty: true
                environment:
                  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                command: --default-authentication-plugin=mysql_native_password
        parsecheck: 
                container_name: parsecheck
                build: 
                        context: ./
                tty: true
                profiles: 
                  - extra

