version: "3"

services:

  mysql80:
    container_name: mysql80
    image: mysql:8
    volumes:
      - ./conf.d/mysql80.cnf:/etc/mysql/mysql.conf.d/mysql80.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password

  mysql57:
    container_name: mysql57
    image: mysql:5.7
    volumes:
      - ./conf.d/mysql57.cnf:/etc/mysql/mysql.conf.d/mysql57.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password
    profiles: 
      - extra

  mysql56:
    container_name: mysql56
    image: mysql:5.6
    volumes:
      - ./conf.d/mysql56.cnf:/etc/mysql/mysql.conf.d/mysql56.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password
    profiles: 
      - extra

  mysql55:
    container_name: mysql55
    image: mysql:5.5
    volumes:
      - ./conf.d/mysql55.cnf:/etc/mysql/mysql.conf.d/mysql55.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    profiles: 
      - extra

  mysql51:
    container_name: mysql51
    image: mtirsel/mysql-5.1
    volumes:
      - ./conf.d/mysql51-my.cnf:/etc/mysql/my.cnf:ro
      - ./conf.d/mysql51.cnf:/etc/mysql/mysql.conf.d/mysql51.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    profiles: 
     - extra

  mssql2019:
    container_name: mssql2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd
    profiles: 
      - extra

  mssql2017:
    container_name: mssql2017
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd
    profiles: 
      - extra

  postgres14:
    container_name: postgres14
    image: postgres:14
    volumes:
      - ./conf.d/postgres14.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    profiles:
      - extra

  postgres13:
    container_name: postgres13
    image: postgres:13
    volumes:
      - ./conf.d/postgres13.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    profiles:
      - extra

  postgres12:
    container_name: postgres12
    image: postgres:12
    volumes:
      - ./conf.d/postgres12.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    profiles:
      - extra

  postgres11:
    container_name: postgres11
    image: postgres:11
    volumes:
      - ./conf.d/postgres11.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    profiles:
      - extra

  postgres10:
    container_name: postgres10
    image: postgres:10
    volumes:
      - ./conf.d/postgres10.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    profiles:
      - extra

  psql: 
    container_name: client
    build: 
      context: ../../utils/client-psql/
    tty: true
    profiles: 
      - extra

  sqlcmd: 
    container_name: client
    build: 
      context: ../../utils/client-sqlcmd/
    tty: true
    profiles: 
      - extra

  mysql: 
    container_name: client
    build: 
      context: ../../utils/client-mysql/
    tty: true
    profiles: 
      - extra