version: "3"

services:
  mysql80:
    container_name: mysql80
    image: mysql:8
    tty: true
    volumes:
      - ./conf.d/mysql80.cnf:/etc/mysql/mysql.conf.d/mysql80.cnf:ro
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  mysql: 
    container_name: client
    build: 
      context: ../../utils/client-mysql/
    tty: true
    profiles: 
      - extra

  sshd:
    container_name: sshd
    build:
      context: ../../utils/sshd/
    tty: true
    privileged: true
    ports:
      - "55251:22"
    profiles:
      - extra