version: "3"

services:
        db51:
                container_name: db51
                image: vsamov/mysql-5.1.73
                tty: true
                privileged: true
                environment:
                  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                  MYMASTER: ""
                volumes: 
                   - ./conf.d/mysql51-my.cnf:/etc/mysql/my.cnf:ro
                   - ./conf.d/mysql51.cnf:/etc/mysql/mysql.conf.d/mysql51.cnf:ro
                   - ./conf.d/docker-entrypoint.sh:/entrypoint.sh:ro
                healthcheck:
                        test: ["CMD-SHELL","mysql -uroot -sNe \"select 1;\""]
                        start_period: 5s
                        retries: 20
                        interval: 1s
                        timeout: 1s

        db55:
                container_name: db55
                image: mysql:5.5
                tty: true
                environment:
                  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                  MYMASTER: "db51"
                volumes: 
                   - ./conf.d/mysql55.cnf:/etc/mysql/conf.d/mysql55.cnf:ro
                   - ./initdb.d:/docker-entrypoint-initdb.d:ro
                healthcheck:
                        test: ["CMD-SHELL","mysql -uroot -sNe \"select 1;\""]
                        start_period: 5s
                        retries: 20
                        interval: 1s
                        timeout: 1s
                depends_on: 
                  db51:
                    condition: service_healthy

        db56:
                container_name: db56
                image: mysql:5.6
                tty: true
                environment:
                  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                  MYMASTER: "db55"
                volumes: 
                   - ./conf.d/mysql56.cnf:/etc/mysql/conf.d/mysql56.cnf:ro
                   - ./initdb.d:/docker-entrypoint-initdb.d:ro
                healthcheck:
                        test: ["CMD-SHELL","mysql -uroot -sNe \"select 1;\""]
                        start_period: 5s
                        retries: 20
                        interval: 1s
                        timeout: 1s
                depends_on: 
                  db55:
                    condition: service_healthy

        db57:
                container_name: db57
                image: mysql:5.7
                tty: true
                environment:
                  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                  MYMASTER: "db56"
                volumes: 
                   - ./conf.d/mysql57.cnf:/etc/mysql/conf.d/mysql57.cnf:ro
                   - ./initdb.d:/docker-entrypoint-initdb.d:ro
                healthcheck:
                        test: ["CMD-SHELL","mysql -uroot -sNe \"select 1;\""]
                        start_period: 5s
                        retries: 20
                        interval: 1s
                        timeout: 1s
                depends_on: 
                  db56:
                    condition: service_healthy

        db80:
                container_name: db80
                image: mysql:8.0
                tty: true
                environment:
                  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                  MYMASTER: "db57"
                volumes: 
                   - ./conf.d/mysql80.cnf:/etc/mysql/conf.d/mysql80.cnf:ro
                   - ./initdb.d:/docker-entrypoint-initdb.d:ro
                command:
                  --default-authentication-plugin=mysql_native_password
                healthcheck:
                        test: ["CMD-SHELL","mysql -uroot -sNe \"select 1;\""]
                        start_period: 5s
                        retries: 20
                        interval: 1s
                        timeout: 1s
                depends_on: 
                  db56:
                    condition: service_healthy

        mysql: 
                container_name: client
                build: 
                        context: ../../utils/client-mysql/
                tty: true
                profiles: 
                  - extra
